import js from '@eslint/js';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import globals from 'globals';

export default [
  {
    // `coverage` is generated by `npm run test:coverage`. Without it here, running
    // coverage locally makes the very next `npm run lint` fail on istanbul's own
    // output — a local-only failure CI never reproduces, because CI lints in a
    // clean checkout.
    ignores: ['dist', 'build', 'coverage', 'node_modules', 'script.js', 'style.css', '.wrangler'],
  },
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.es2020,
        ...globals.node,
        ...globals.jest,
        vi: 'readonly',
        global: 'readonly',
        process: 'readonly',
      },
    },
    plugins: {
      react,
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      'jsx-a11y': jsxA11y,
    },
    rules: {
      ...js.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      // eslint-plugin-react-hooks v7 (pulled in for eslint 10 support) turns on
      // React-Compiler-oriented rules by default. These two flag intentional,
      // working patterns here — rAF-driven setState in useCountUp, and the
      // error-reporting store — that aren't defects, so we opt out of them
      // rather than refactor sound code. rules-of-hooks + exhaustive-deps (the
      // rules that catch real hook bugs) stay on.
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/immutability': 'off',
      'jsx-a11y/alt-text': 'error',
      'jsx-a11y/anchor-is-valid': 'error',
      'react/no-unescaped-entities': 'off',
      'no-console': 'off',
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
    settings: {
      react: {
        version: '19.2',
      },
    },
  },
  {
    files: ['server/**/*.js', 'worker.js'],
    rules: {
      'no-unused-vars': 'off',
    },
  },
];
